#!/bin/bash
# /etc/init.d/pi-radio
#

### BEGIN INIT INFO
# Provides:          pi-radio
# Required-Start:    $local_fs networking mpd 
# Required-Stop:     $local_fs
# Should-Start:      $network mpd
# Should-Stop:       $network mpd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry Pi Internet Radio
# Description:       Start the Raspberry Pi Internet Radio service 
#                    to control local mpd via Arduino-based front-end
### END INIT INFO

PI_RADIO_DIR=/home/pi/PiRadio


# Some things that run always
touch /var/lock/pi-radio

if [[ $(whoami) != "root" ]]; then
  echo "run as root"
  exit 1
fi

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script pi-radio "
    if [[ -e /var/run/pi-radio.pid ]]; then
      PID=$(cat /var/run/pi-radio.pid)
      if (ps -p $PID); then
        echo "already running"
        exit
      fi
    fi
    cd $PI_RADIO_DIR
    php radio.php &
    echo $! > /var/run/pi-radio.pid
    ;;
  stop)
    if [[ -e /var/run/pi-radio.pid ]]; then
      echo "Stopping script pi-radio"
      PID=$(cat /var/run/pi-radio.pid)
      kill $PID
      rm /var/run/pi-radio.pid
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/pi-radio {start|stop}"
    exit 1
    ;;
esac

exit 0